In [1]:
# Nutritional values: [Carbs, Protein, Fat]
foods = {
    "Apples":   [56.0, 1.2, 1.8],
    "Beef":     [0.0, 104.0, 135.0],
    "Eggs":     [4.4, 52.0, 99.0],
    "Potatoes": [68.0, 8.0, 0.9]
}

# Display the values
for food, values in foods.items():
    print(f"{food}: Carbs={values[0]}, Protein={values[1]}, Fat={values[2]}")


Apples: Carbs=56.0, Protein=1.2, Fat=1.8
Beef: Carbs=0.0, Protein=104.0, Fat=135.0
Eggs: Carbs=4.4, Protein=52.0, Fat=99.0
Potatoes: Carbs=68.0, Protein=8.0, Fat=0.9


In [2]:
import numpy as np
A=np.array([[56.0, 0.0, 4.4, 68.0], [1.2, 104.0,52.0,8.0], [1.8, 135.0, 99.0, 0.9]])


In [3]:
print(A)

[[ 56.    0.    4.4  68. ]
 [  1.2 104.   52.    8. ]
 [  1.8 135.   99.    0.9]]


In [5]:
cal=A.sum(axis=0)
print(cal)

[ 59.  239.  155.4  76.9]


In [7]:
cal_reshape=cal.reshape(1,4)
print(cal_reshape)

[[ 59.  239.  155.4  76.9]]


In [6]:
percentage=100*A/cal.reshape(1,4)
print(percentage)

[[94.91525424  0.          2.83140283 88.42652796]
 [ 2.03389831 43.51464435 33.46203346 10.40312094]
 [ 3.05084746 56.48535565 63.70656371  1.17035111]]
